from fastapi import FastAPI
from pydantic import BaseModel
import uvicorn
from dotenv import load_dotenv
import os

# 1. Load Environment Variables (Biar aman)
load_dotenv()

# Cek apakah API Key terbaca (Hanya buat debug awal, hapus nanti)
if not os.getenv("OPENAI_API_KEY"):
    print("⚠️  BAHAYA: API Key belum di-set di file .env!")
else:
    print("✅  Aman: API Key terdeteksi.")

# 2. Inisialisasi App
app = FastAPI(
    title="SaaS E-commerce Automation AI",
    description="Backend API untuk generate produk otomatis pakai CrewAI",
    version="1.0.0"
)

# 3. Struktur Data (Schema) buat komunikasi sama Frontend
class ProductRequest(BaseModel):
    image_url: str = None  # Nanti diisi path gambar yg diupload
    user_notes: str = ""   # Catatan tambahan dari user
    platform: str = "shopee"

# 4. Endpoint Test (Health Check)
@app.get("/")
def read_root():
    return {"status": "Online", "message": "Backend SaaS siap tempur! 🚀"}

# 5. Endpoint Generate (Simulasi Dulu)
@app.post("/generate-product")
def generate_product_details(request: ProductRequest):
    # Nanti logika CrewAI masuk disini
    return {
        "status": "success",
        "data": {
            "title_suggestion": "Tas Kulit Vintage Premium - [Generated by AI]",
            "description_suggestion": "Tas ini cocok banget buat kuliah...",
            "price_suggestion": 150000
        }
    }

# Biar bisa dijalankan langsung dengan 'python main.py'
if __name__ == "__main__":
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)